// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: proto/recorder.proto

package recorder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event message definition.
type StartRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoiceChannelId string `protobuf:"bytes,1,opt,name=voiceChannelId,proto3" json:"voiceChannelId,omitempty"`
	Roll20GameId   string `protobuf:"bytes,2,opt,name=roll20GameId,proto3" json:"roll20GameId,omitempty"`
}

func (x *StartRecordRequest) Reset() {
	*x = StartRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_recorder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecordRequest) ProtoMessage() {}

func (x *StartRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecordRequest.ProtoReflect.Descriptor instead.
func (*StartRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{0}
}

func (x *StartRecordRequest) GetVoiceChannelId() string {
	if x != nil {
		return x.VoiceChannelId
	}
	return ""
}

func (x *StartRecordRequest) GetRoll20GameId() string {
	if x != nil {
		return x.Roll20GameId
	}
	return ""
}

type StartRecordReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Discord bool `protobuf:"varint,1,opt,name=discord,proto3" json:"discord,omitempty"`
	Roll20  bool `protobuf:"varint,2,opt,name=roll20,proto3" json:"roll20,omitempty"`
}

func (x *StartRecordReply) Reset() {
	*x = StartRecordReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_recorder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRecordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecordReply) ProtoMessage() {}

func (x *StartRecordReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecordReply.ProtoReflect.Descriptor instead.
func (*StartRecordReply) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{1}
}

func (x *StartRecordReply) GetDiscord() bool {
	if x != nil {
		return x.Discord
	}
	return false
}

func (x *StartRecordReply) GetRoll20() bool {
	if x != nil {
		return x.Roll20
	}
	return false
}

type StopRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoiceChannelId string `protobuf:"bytes,1,opt,name=voiceChannelId,proto3" json:"voiceChannelId,omitempty"`
	Roll20GameId   string `protobuf:"bytes,2,opt,name=roll20GameId,proto3" json:"roll20GameId,omitempty"`
}

func (x *StopRecordRequest) Reset() {
	*x = StopRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_recorder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordRequest) ProtoMessage() {}

func (x *StopRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordRequest.ProtoReflect.Descriptor instead.
func (*StopRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{2}
}

func (x *StopRecordRequest) GetVoiceChannelId() string {
	if x != nil {
		return x.VoiceChannelId
	}
	return ""
}

func (x *StopRecordRequest) GetRoll20GameId() string {
	if x != nil {
		return x.Roll20GameId
	}
	return ""
}

type StopRecordReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiscordKeys []string `protobuf:"bytes,1,rep,name=discordKeys,proto3" json:"discordKeys,omitempty"`
	Roll20Key   string   `protobuf:"bytes,2,opt,name=roll20Key,proto3" json:"roll20Key,omitempty"`
}

func (x *StopRecordReply) Reset() {
	*x = StopRecordReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_recorder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRecordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordReply) ProtoMessage() {}

func (x *StopRecordReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordReply.ProtoReflect.Descriptor instead.
func (*StopRecordReply) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{3}
}

func (x *StopRecordReply) GetDiscordKeys() []string {
	if x != nil {
		return x.DiscordKeys
	}
	return nil
}

func (x *StopRecordReply) GetRoll20Key() string {
	if x != nil {
		return x.Roll20Key
	}
	return ""
}

var File_proto_recorder_proto protoreflect.FileDescriptor

var file_proto_recorder_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x22, 0x60, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x72, 0x6f, 0x6c, 0x6c, 0x32, 0x30, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x6f, 0x6c, 0x6c, 0x32, 0x30, 0x47, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x22, 0x44, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x6c, 0x32, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x6c, 0x32, 0x30, 0x22, 0x5f, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x0e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x6f, 0x6c, 0x6c, 0x32, 0x30, 0x47,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x6f, 0x6c,
	0x6c, 0x32, 0x30, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x0f, 0x53, 0x74, 0x6f,
	0x70, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x6c, 0x32, 0x30, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x6f, 0x6c, 0x6c, 0x32, 0x30, 0x4b, 0x65, 0x79, 0x32, 0x92, 0x01, 0x0a,
	0x0d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3e, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x1b, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_recorder_proto_rawDescOnce sync.Once
	file_proto_recorder_proto_rawDescData = file_proto_recorder_proto_rawDesc
)

func file_proto_recorder_proto_rawDescGZIP() []byte {
	file_proto_recorder_proto_rawDescOnce.Do(func() {
		file_proto_recorder_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_recorder_proto_rawDescData)
	})
	return file_proto_recorder_proto_rawDescData
}

var file_proto_recorder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_recorder_proto_goTypes = []interface{}{
	(*StartRecordRequest)(nil), // 0: recorder.StartRecordRequest
	(*StartRecordReply)(nil),   // 1: recorder.StartRecordReply
	(*StopRecordRequest)(nil),  // 2: recorder.StopRecordRequest
	(*StopRecordReply)(nil),    // 3: recorder.StopRecordReply
}
var file_proto_recorder_proto_depIdxs = []int32{
	0, // 0: recorder.RecordService.Start:input_type -> recorder.StartRecordRequest
	2, // 1: recorder.RecordService.Stop:input_type -> recorder.StopRecordRequest
	1, // 2: recorder.RecordService.Start:output_type -> recorder.StartRecordReply
	3, // 3: recorder.RecordService.Stop:output_type -> recorder.StopRecordReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_recorder_proto_init() }
func file_proto_recorder_proto_init() {
	if File_proto_recorder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_recorder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_recorder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRecordReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_recorder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_recorder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopRecordReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_recorder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recorder_proto_goTypes,
		DependencyIndexes: file_proto_recorder_proto_depIdxs,
		MessageInfos:      file_proto_recorder_proto_msgTypes,
	}.Build()
	File_proto_recorder_proto = out.File
	file_proto_recorder_proto_rawDesc = nil
	file_proto_recorder_proto_goTypes = nil
	file_proto_recorder_proto_depIdxs = nil
}
